### ISSUE TITLE
Wrong considered question views.

### ISSUE THREAD

**Issue by yerbol89** [sama55/q2a-caching#12]
Wrong considered question views.
Today i see my site.
Question view count normal work for login user. And anonym user views question dont it counts the number of.

p.s. sorry my bad english. i use google translate.

**Comment by sama55** [comment]
Cache plugin will skip a lot of processing of Q2A. Therefore, you pointed out might be correct. I'll try to investigate. Because my English is very bad, please do not worry about your English.

**Comment by sama55** [comment]
I fixed in V0.5. Please test it.

**Comment by yerbol89** [comment]
@sama55  Cool. Thanks!
