### ISSUE TITLE
Maximum number of cache files in one folder

### ISSUE THREAD

**Issue by sama55** [sama55/q2a-caching#13]
Maximum files in one directory are 31,998 in case of CentOS (ext3 file system). In case of large site, it will exceed this limit. We need to determine the number of cache files that are stored in a single folder. And, cache files need to be stored in a distributed in multiple folders. By the way, uploaded images are stored in blob table. This is some pros and cons. However, it is one way to not mind file system limitations.

**Comment by stevenev** [comment]
Hi Sama55, I downloaded the plugin, working just fine.  I also managed to sign in, so the form token is working fine.  I thought one could not sign on as security token was not properly set. Please help

**Comment by stevenev** [comment]
I have previously implemented up to 3 subdirectories deep to avoid such limits.  But then management becomes a headache.  Propose moving to mysql cache table, as detailed here: http://www.question2answer.org/qa/46780/core-proposal-general-cache

**Comment by sama55** [comment]
I agree. In the first version, I will store to the DB. However, it might be disliked by some users. I might tackle it as improvement matters for next version.

**Comment by stevenev** [comment]
ok, sounds good.  Then some cache writes would fail.  The system should still work fine with whatever is cached (I would think, but maybe worth testing at some point).

**Comment by stevenev** [comment]
I am guessing if max directory limit is reached, this will fail:

file_put_contents( ...

and will put out a warning.  I think doing 
@file_put_contents( ...

Would suppress warning, and that should be good enough. The system simply would not write that cache entry on next page load.

**Comment by sama55** [comment]
Fixed in V0.6 (7/27).
