### ISSUE TITLE
Recursive Delete - need change

### ISSUE THREAD

**Issue by stevenev** [sama55/q2a-caching#21]
The script includes recursive delete of cached files.  If there are thousands of files, that could get very long.  php's "unlink" accepts wildcard, so that should be used instead.

**Comment by sama55** [comment]
Thanks steven.
I thought unlink function does not allow wild card. And, rmdir can delete only empty folders. Your pointed out that the glob? Probably, it is slower than low-level functions. Is my understanding would be wrong?

**Comment by stevenev** [comment]
I thought you could do wildcard with unlink, but looks like cannot -as you say.

At the top of recursive, one can put
@exec( 'rm dirname/*);
@exec( 'del dirname/*);

This would take care of windows and linux, and if they fail (i.e. exec not permitted) recursive will take care of it.  And if they succeed, recursive will not find any files to delete.

**Comment by sama55** [comment]
Yes. If we use shell, it is possible. But probably it is slow.
...
I was more thinking. This part is the most time-consuming process in the plugin. For example, if plugin remove 10,000 files, it would be need very long time. In this sense, it may be necessary to remove files with asynchronous (background) process.
e.g.: @exec( 'del dirname/ * &);
Um ...

**Comment by stevenev** [comment]
I think you are right.  Note good idea to do wildcard delete...

one can use
@exec( 'rm -rf dirname; mkdir dirname' );

The whole thing can be put in background per your idea, but I am not sure that is necessary.  Should be pretty fast, but I have not tried.  In anycase, should not happen often.
