### ISSUE TITLE
Fallback in case of cache failure

### ISSUE THREAD

**Issue by stevenev** [sama55/q2a-caching#23]
in private function get_cache() 

if the cache fails for any reason, the system just exits, and a blank page is shown.  Suggest it would gracefully allow the normal page to be rendered (nice to be out an error log of course).

**Comment by sama55** [comment]
I do not yet turning a hand up to the error handling. ^_^;;
However, it would be necessary. It's resulting story, after this, cache data will be saved into DB and read from DB. In other words, Insert and delete query will be executed. If error had occurred in this procedure, error message will be displayed by qa_page_db_fail_handler.
See L146
=> qa_db_connect('qa_page_db_fail_handler') in qa-db.php
=> qa_db_fail_error() in qa-db.php
=> qa_page_db_fail_handler() in qa-page.php
