### ISSUE TITLE
Suggestion: Locate cache directory into the plugin directory

### ISSUE THREAD

**Issue by stevenev** [sama55/q2a-caching#24]
Suggest the cache directory to live within the plugin directory, and not to affect the core structure.

**Comment by stevenev** [comment]
define('QA_CACHING_DIR', dirname(__FILE__) . '/qa-cache'); //Cache Directory

**Comment by stevenev** [comment]
`define('QA_CACHING_DIR', dirname(__FILE__) . '/qa-cache'); //Cache Directory`

**Comment by sama55** [comment]
Fixed in V0.6(7/27)
