### ISSUE TITLE
How i add for Excluded requests add 404 page

### ISSUE THREAD

**Issue by yerbol89** [sama55/q2a-caching#4]
My site i install cache plugin. Its nice work. But this plugin generate html file.
And generated 404 page not fine. Status this not found page 200 OK
How i Excluding 404 Pages from q2a-caching.

**Comment by sama55** [comment]
In my test, 404 error page is cached. But, I do not understand it's problem.
Please explain your issue with screen capture.

**Comment by sama55** [comment]
I changed program in V0.3. Try it.

**Comment by yerbol89** [comment]
@sama55 yes. Plugin generate 404 error page cached. After this page not 404 page. Its html file page, not 404 page. Server for Google bot not views this page 404 page. Google understands how html file page.
Example: http://check-host.net/check-http?host=http://szh.kz/dawdwad&lang=en
http://check-host.net/check-http?host=http://www.question2answer.org/qa/dawdawdw&lang=en

![111](https://cloud.githubusercontent.com/assets/993795/8763587/631ebaa2-2dc6-11e5-9469-424aca331301.png)
![333](https://cloud.githubusercontent.com/assets/993795/8763588/63238988-2dc6-11e5-8978-e465ffc8481e.png)

**Comment by sama55** [comment]
Thanks yerbol. I understood it. Try V0.3.

**Comment by yerbol89** [comment]
@sama55 thanks. Its nice work.
