### ISSUE TITLE
Expiration time: seconds dont nice work

### ISSUE THREAD

**Issue by yerbol89** [sama55/q2a-caching#41]
I see my site for unregistered users create cache file dont nice work. I add 3600 seconds. But site create new file after 1-2 min. Please you can see that it's not working properly. I enable Output debug comment:

**Comment by yerbol89** [comment]
After new post create new html file.

**Comment by sama55** [comment]
It is plugin's specification. You can customize with caching option (Expiration events:) in admin panel.

**Comment by yerbol89** [comment]
@sama55 I add for config 3600 seconds. But cache dont save 1 hours. New cache create after 1-2 minuts.

**Comment by sama55** [comment]
Can you not understand my answers above?

**Comment by yerbol89** [comment]
@sama55 
https://www.youtube.com/watch?v=l3bfp0LfTEY&

**Comment by sama55** [comment]
Set empty (blank) to "Expiration events: (Comma-separated):".
(This is not "Expiration time")
