### ISSUE TITLE
Log file i see error log on line 88

### ISSUE THREAD

**Issue by yerbol89** [sama55/q2a-caching#5]
[Sun Jul 19 04:00:23 2015] [error] [client 54.244.59.129] PHP Warning:  file_put_contents(): Filename cannot be empty in /var/www/szh/data/www/szh.kz/qa-plugin/q2a-caching/qa-caching-main.php on line 88, referer: http://szh.kz/2018/sharigat-aitqanyndy-ushinshi-tyndamasa-ushinshiden-zherinen

[Sun Jul 19 04:00:34 2015] [error] [client 217.76.76.40] PHP Warning:  file_put_contents(): Filename cannot be empty in /var/www/szh/data/www/szh.kz/qa-plugin/q2a-caching/qa-caching-main.php on line 88

**Comment by sama55** [comment]
Probably, it is bug of original plugin. I fixed in V0.3 now. Try it.

**Comment by sama55** [comment]
This error occurs in newest (V0.5) version?

**Comment by yerbol89** [comment]
@sama55 thanks. Its fixed.
